### ISSUE TITLE
nxstyle should not complain on _Exit

### ISSUE THREAD

**Issue by yamt** [apache/incubator-nuttx#1235]
e.g.

    % nxstyle stdlib.h
    stdlib.h:152:19: error: Mixed case identifier found

**Comment by v01d** [comment]
Maybe nxstyle could be extended to recognize some special comment that instructs to ignore a line (or at least a given rule for that line)

**Comment by patacongo** [comment]
> 
> 
> Maybe nxstyle could be extended to recognize some special comment that instructs to ignore a line (or at least a given rule for that line)

This has been discussed and I, for one, have been very opposed to corrupting good, clean C files with meta-data for nxstyle.  People have talked about a lot of things and we have done the best we can to squash that approach.

**Comment by yamt** [comment]
for this specific case (_Exit), as it's a part of the standards, it's more appropriate to make nxstyle itself know, IMO.

**Comment by Ouss4** [comment]
There already is a white list in nxstyle.c, we can just add `_Exit` to the list.
```diff
diff --git a/tools/nxstyle.c b/tools/nxstyle.c
index 78351334bf..38b89f98df 100644
--- a/tools/nxstyle.c
+++ b/tools/nxstyle.c
@@ -192,6 +192,7 @@ static const char *g_white_prefix[] =
   "ub8",     /* Ref:  include/fixedmath.h */
   "ub16",    /* Ref:  include/fixedmath.h */
   "ub32",    /* Ref:  include/fixedmath.h */
+  "_Exit",   /* Ref:  include/stdlib.h */
   NULL
 };
```
