### ISSUE TITLE
Missing LICENSE and NOTICE file

### ISSUE THREAD

**Issue by justinmclean** [apache/incubator-nuttx#126]
All ASF project need a LICENSE and NOTICE file. I note view license is pointing to COPYING which contains possible out of date information.

**Comment by fpj** [comment]
Adding the how-to guide reference for LICENSE and NOTICE files:

http://www.apache.org/dev/licensing-howto.html

**Comment by btashton** [comment]
I'm working on getting an initial stab at this including the headers for easy files, but it won't be ready until I'm back next week.
