### ISSUE TITLE
nfs problem

### ISSUE THREAD

**Issue by daipipiwan12** [apache/incubator-nuttx#1495]
hello,
   when using nfs component from the nuttx system, we find a problem in the following case:
rm abc
rm error: Permission denied
abc file is a directory.
the nfs server is haneWIN on win10.
In this case, we wish to get an errno equal to EISDIR , however, the errno is EACCES here.
Have you ever met this problem?

thanks)

**Comment by acassis** [comment]
Could you please supply more details? Did you try using a Linux NFS server?
If it is a haneWIN issue only we need to do further investigation.

**Comment by v01d** [comment]
I'm closing this since OP did not provide further details for more than half a year.
@daipipiwan12 feel free to reopen if the issue persists and provide more detail in that case.
