### ISSUE TITLE
Numerous obsoleted URLs in repository:

### ISSUE THREAD

**Issue by patacongo** [apache/incubator-nuttx#1498]
Lot's of old references to the old nuttx.org DocuWiki still exist:

    $ grep -r "nuttx[.]org" * | grep http
    
    arch/arm/src/armv7-m/Kconfig:           http://www.nuttx.org/doku.php?id=wiki:nxinternal:svcall
    arch/arm/src/armv8-m/Kconfig:           http://www.nuttx.org/doku.php?id=wiki:nxinternal:svcall
    arch/Kconfig:           paging feature as described in http://www.nuttx.org/NuttXDemandPaging.html.
    
    boards/arm/cxd56xx/spresense/configs/rndis/defconfig:CONFIG_NSH_WGET_USERAGENT="NuttX/7.2x.x (; http://www.nuttx.org/)"
    boards/arm/cxd56xx/spresense/configs/wifi/defconfig:CONFIG_NSH_WGET_USERAGENT="NuttX/7.2x.x (; http://www.nuttx.org/)"
    boards/arm/lc823450/lc823450-xgevk/configs/bt/defconfig:CONFIG_NSH_WGET_USERAGENT="NuttX/7.2x.x (; http://www.nuttx.org/)"
    boards/arm/lc823450/lc823450-xgevk/configs/krndis/defconfig:CONFIG_NSH_WGET_USERAGENT="NuttX/7.2x.x (; http://www.nuttx.org/)"
    boards/arm/lc823450/lc823450-xgevk/configs/rndis/defconfig:CONFIG_NSH_WGET_USERAGENT="NuttX/7.2x.x (; http://www.nuttx.org/)"
    boards/arm/lpc17xx_40xx/olimex-lpc1766stk/README.txt:      See http://www.nuttx.org/doku.php?id=wiki:vfs:nxflat#toolchain_compatibility_problem
    boards/arm/lpc17xx_40xx/u-blox-c027/configs/nsh/defconfig:CONFIG_NSH_WGET_USERAGENT="NuttX/7.xx.x (; http://www.nuttx.org/)"
    boards/arm/lpc31xx/ea3131/README.txt:    paging enabled.  See http://www.nuttx.org/Documentation/NuttXDemandPaging.html.
    boards/arm/sam34/flipnclick-sam3x/README.txt:   You can find photos my setup here: http://www.nuttx.org/doku.php?id=wiki:howtos:flipnclick-sam3x
    boards/arm/sama5/sama5d2-xult/README.txt:       http://nuttx.org/doku.php?id=wiki:howtos:syslog . Relevant
    boards/arm/sama5/sama5d4-ek/README.txt:                 http://www.nuttx.org/doku.php?id=wiki:nxinternal:memconfigs#task_create
    boards/arm/sama5/sama5d4-ek/README.txt:       http://nuttx.org/doku.php?id=wiki:howtos:syslog . Relevant
    boards/arm/samv7/samv71-xult/README.txt:       http://nuttx.org/doku.php?id=wiki:howtos:syslog . Relevant
    boards/arm/stm32/clicker2-stm32/README.txt:       http://nuttx.org/doku.php?id=wiki:howtos:syslog . Relevant
    boards/arm/stm32/stm32f4discovery/README.txt:            http://www.nuttx.org/doku.php?id=wiki:howtos:stm32-ccm-alloc
    boards/arm/stm32/stm32f4discovery/README.txt:     http://www.nuttx.org/doku.php?id=wiki:graphics:nxgraphics for a description
    boards/arm/stm32f7/stm32f746g-disco/README.txt:  http://www.nuttx.org/doku.php?id=wiki:howtos:port-drivers_stm32f7
    boards/README.txt:http://nuttx.org/Documentation/NuttXConfigVariables.html.
    
    Documentation/NuttX.html:        (see the <a href="http://www.nuttx.org/Documentation/NuttShell.html">NSH User Guide</a>).
    Documentation/NuttX.html:      (see the <a href="http://www.nuttx.org/Documentation/NuttShell.html">NSH User Guide</a>).
    Documentation/NuttX.html:          The configuration that was used to verify the Nuttx <a href="http://www.nuttx.org/doku.php?id=wiki:nxinternal:highperfints">high-priority, nested interrupt feature</a>.
    Documentation/NuttX.html:        <a href=" http://www.nuttx.org/Documentation/NXGraphicsSubsystem.html">NX graphics system</a>.
    Documentation/NuttX.html:        As of this writing, the basic Arduino Due port is code complete and a fully verified configuration exists for the NuttShell <a href="http://www.nuttx.org/Documentation/NuttShell.html">NSH</a>).
    Documentation/NuttX.html:        (see the <a href="http://www.nuttx.org/Documentation/NuttShell.html">NSH User Guide</a>).
    Documentation/NuttX.html:        Verified configurations are now available for the NuttShell with networking and microSD support(NSH, see the <a href="http://www.nuttx.org/Documentation/NuttShell.html">NSH User Guide</a>),
    Documentation/NuttX.html:        In NuttX-6.27 there is a working basic port with OS verification, Nuttshell (<a href="http://www.nuttx.org/Documentation/NuttShell.html">NSH</a>) configurations, and a graphics test configuration.
    Documentation/NuttX.html:        <a href="http://www.nuttx.org/Documentation/NuttShell.html">NSH User Guide</a>).
    Documentation/NuttX.html:          <a href="http://www.nuttx.org/Documentation/NuttShell.html">NSH User Guide</a>) as well as several other configurations.
    Documentation/NuttX.html:        As of this writing, the basic port is code complete and a fully verified configuration exists for the NuttShell <a href="http://www.nuttx.org/Documentation/NuttShell.html">NSH</a>).
    Documentation/NuttX.html:        This basic board support included a configuration for the NuttShell <a href="http://www.nuttx.org/Documentation/NuttShell.html">NSH</a>).
    Documentation/NuttX.html:            This basic board support included a configuration for the NuttShell <a href="http://www.nuttx.org/Documentation/NuttShell.html">NSH</a>) and a configuration for testing IPv6.
    Documentation/NuttX.html:            This board supports included two configurations for the NuttShell (<a href="http://www.nuttx.org/Documentation/NuttShell.html">NSH</a>).
    Documentation/NuttX.html:        As of this writing, the basic port is code complete and a fully verified configuration exists for the NuttShell <a href="http://www.nuttx.org/Documentation/NuttShell.html">NSH</a>).
    Documentation/NuttX.html:      (see the <a href="http://www.nuttx.org/Documentation/NuttShell.html">NSH User Guide</a>).
    Documentation/NuttX.html:          As of this writing, the basic port is code complete and a fully verified configuration exists for the NuttShell <a href="http://www.nuttx.org/Documentation/NuttShell.html">NSH</a>).
    Documentation/NuttX.html:          As of this writing, the basic port is code complete and a fully verified configuration exists for the NuttShell <a href="http://www.nuttx.org/Documentation/NuttShell.html">NSH</a>).
    Documentation/NuttX.html:      (see the <a href="http://www.nuttx.org/Documentation/NuttShell.html">NSH User Guide</a>).
    Documentation/NuttX.html:          The STM32 F7 peripherals are very similar to some members of the STM32 F4 and additional drivers can easily be ported the F7 as discussed in this Wiki page: <a href="http://www.nuttx.org/doku.php?id=wiki:howtos:port-drivers_stm32f7">Porting Drivers to the STM32 F7</a>
    Documentation/NuttX.html:         <a href="http://www.nuttx.org/Documentation/NuttShell.html">NSH User Guide</a>).
    Documentation/NuttX.html:          A NuttShell (NSH) configuration is in place (see the <a href="http://www.nuttx.org/Documentation/NuttShell.html">NSH User Guide</a>).
    Documentation/NuttX.html:        See the <a href="http://www.nuttx.org/Documentation/NuttShell.html">NSH User Guide</a> for further information about NSH.
    Documentation/NuttX.html:       Available configurations include the NuttShell (NSH - see the <a href="http://www.nuttx.org/Documentation/NuttShell.html">NSH User Guide</a>).
    Documentation/NuttX.html:      Available configurations include the NuttShell (NSH - see the <a href="http://www.nuttx.org/Documentation/NuttShell.html">NSH User Guide</a>).
    Documentation/NuttX.html:      Available configurations include the NuttShell (NSH - see the <a href="http://www.nuttx.org/Documentation/NuttShell.html">NSH User Guide</a>).
    Documentation/NuttxPortingGuide.html:For a technical description of the NuttX implementation of SMP, see the NuttX <a href="http://www.nuttx.org/doku.php?id=wiki:nxinternal:smp">SMP Wiki Page</a>.
    Documentation/NuttxPortingGuide.html:  The version of <code>NuttXConfigVariables.html</code> for the last released version of NuttX can also be found <a href="http://nuttx.org/Documentation/NuttXConfigVariables.html">online</a>.
    Documentation/NuttxUserGuide.html:  Non-standard extensions to VxWorks-like interfaces to support POSIX <a href="http://www.nuttx.org/doku.php?id=wiki:nxinternal:cancellation-points">Cancellation Points</a>.
    Documentation/NuttxUserGuide.html:  task deletion is deferred if cancellation is disabled or if deferred cancellation is supported (with <a href="http://www.nuttx.org/doku.php?id=wiki:nxinternal:cancellation-points">Cancellation Points</a> enabled).
    Documentation/NuttxUserGuide.html:The <code>task_testcancel()</code> function creates a <a href="http://www.nuttx.org/doku.php?id=wiki:nxinternal:cancellation-points">Cancellation Point</a> in the calling task.
    Documentation/NuttxUserGuide.html:  This is discussed in much more detail on this <a href="http://www.nuttx.org/doku.php?id=wiki:howtos:signalling-semaphores">Wiki page</a>.
    Documentation/NuttxUserGuide.html:<p>When cancellability is deferred, all cancellations are held pending in the target thread until the thread changes the cancellability type or a <a href="http://www.nuttx.org/doku.php?id=wiki:nxinternal:cancellation-points">Cancellation Point</a> function such as <a href="#pthreadtestcancel"><code>pthread_testcancel()</code></a> is entered.</p>
    Documentation/NuttxUserGuide.html:The <code>pthread_testcancel()</code> function creates a <a href="http://www.nuttx.org/doku.php?id=wiki:nxinternal:cancellation-points">Cancellation Point</a> in the calling thread.
    Documentation/NxWidgets.html:    <a href="http://nuttx.org/nxwidgets_v1_19/html/index.html">Documentation</a>,
    Documentation/redirect.html:<meta http-equiv="REFRESH" content="5;url=http://nuttx.org"></HEAD>
    Documentation/redirect.html:  The NuttX RTOS web site has moved to <a href="http://nuttx.org">nuttx.org</a>.
    
    INVIOLABLES.txt:  http://www.nuttx.org/doku.php?id=documentation:codingstandard
    
    README.md:<http://www.nuttx.org/doku.php?id=wiki:howtos:convertconfig>).
    README.md:  > A: Refer to <http://www.nuttx.org/doku.php?id=wiki:howtos:convertconfig>
    README.md:<http://www.nuttx.org/doku.php?id=wiki:howtos:convertconfig>).
    README.md:NuttX documentation is also available online at <http://www.nuttx.org>.
    
    ReleaseNotes:    http://www.nuttx.org/NuttxUserGuide.html#priorityinheritance.
    ReleaseNotes:    See http://www.nuttx.org/NuttXNxFlat.html.
    ReleaseNotes:    (http://www.nuttx.org/NuttXNxFlat.html)
    ReleaseNotes:http://www.nuttx.org/NXGraphicsSubsystem.html).
    ReleaseNotes:    (see the http://www.nuttx.org/NuttShell.html).
    ReleaseNotes:    was completed (see http://www.nuttx.org/NuttXDemandPaging.html)
    ReleaseNotes:    http://www.nuttx.org/NuttXDemandPaging.html.  Some additional
    ReleaseNotes:    Guide at http://www.nuttx.org/NuttShell.html). Testing of that
    ReleaseNotes:    see the NSH User Guide at http://www.nuttx.org/NuttShell.html.
    ReleaseNotes:http://www.nuttx.org/NuttShell.html), for the NuttX network test,
    ReleaseNotes:    at http://www.nuttx.org/NuttShell.html).
    ReleaseNotes:        http://www.nuttx.org/doku.php?id=wiki:nxinternal:highperfints
    ReleaseNotes:  http://www.nuttx.org/doku.php?id=wiki:howtos:convertconfig for some
    ReleaseNotes:        http://www.nuttx.org/doku.php?id=documentation:codingstandard
    ReleaseNotes:        http://www.nuttx.org/doku.php?id=wiki:howtos:convertconfig for some
    ReleaseNotes:      http://www.nuttx.org/doku.php?id=wiki:nxinternal:memconfigs#the_roadmap_toward_processes
    ReleaseNotes:      http://www.nuttx.org/doku.php?id=wiki:nxinternal:memconfigs#the_roadmap_toward_processes
    ReleaseNotes:        http://www.nuttx.org/doku.php?id=wiki:howtos:ipv6#ethernet_driver_requirements
    ReleaseNotes:      http://www.nuttx.org/doku.php?id=wiki:nxinternal:memconfigs#the_roadmap_toward_processes
    ReleaseNotes:      http://www.nuttx.org/doku.php?id=wiki:nxinternal:memconfigs#the_roadmap_toward_processes
    ReleaseNotes:      http://www.nuttx.org/doku.php?id=wiki:nxinternal:memconfigs#the_roadmap_toward_processes
    ReleaseNotes:      http://www.nuttx.org/doku.php?id=wiki:nxinternal:memconfigs#the_roadmap_toward_processes
    ReleaseNotes:        http://www.nuttx.org/doku.php?id=wiki:nxinternal:smp.  The
    ReleaseNotes:        guide: http://www.nuttx.org/doku.php?id=documentation:portingguide.
    ReleaseNotes:        http://www.nuttx.org/doku.php?id=wiki:howtos:smallvectors .  This
    
    TODO:               http://www.nuttx.org/NuttXDemandPaging.html.
    TODO:                work with (http://www.nuttx.org) and I discovered after doing the
    TODO:                  See http://www.nuttx.org/doku.php?id=wiki:nxinternal:tasksnthreads.
    TODO:               http://www.nuttx.org/doku.php?id=wiki:nxinternal:simulator

**Comment by btashton** [comment]
I'm updating all the references in the OS repo now and should have something up for review.
