### ISSUE TITLE
Resource leak

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [apache/incubator-nuttx#1576]
Stream is opened
https://github.com/apache/incubator-nuttx/blob/294fdd80a946168e09591a742df0480cce2b8a63/tools/cxd56/mkspk.c#L166

Opened file never closed
https://github.com/apache/incubator-nuttx/blob/294fdd80a946168e09591a742df0480cce2b8a63/tools/cxd56/mkspk.c#L175

**Comment by Ouss4** [comment]
That's a tool used to generate spk images for Spresense board.
When the process exits (through the return of main or directly by calling exit()) a clean shutdown of the standard library is performed, i.e. fclose is called for all open streams.

**Comment by jerpelea** [comment]
LGTM

**Comment by Ouss4** [comment]
I'll close this.  @QiAnXinCodeSafe if you have any objection please re-open it.
