### ISSUE TITLE
SPI half duplex driver

### ISSUE THREAD

**Issue by artemopolus** [apache/incubator-nuttx#1659]
I am interesting about Nuttx for implementing in our device. Now we use FreeRTOS on stm32f103cb6, but it's interesting for us to port our software on Nuttx.
 
Basic question is how to add spi half duplex driver in this OS. We have sensor which is working on half duplex spi wire. We found spi_bus_initialize function, but there is no necessary function in this file. What is the best way to implement this driver in OS?
 
Current code perfectly work on FreeRTOS:
 
Using register we need this for spi base configring:
 
#define WRITE_REG(REG, VAL)   ((REG) = (VAL))
#define READ_REG(REG)         ((REG))
#define MODIFY_REG(REG, CLEARMASK, SETMASK)  WRITE_REG((REG), (((READ_REG(REG)) & (~(CLEARMASK))) | (SETMASK)))
 
RCC->APB2ENR |= RCC_APB2ENR_SPI1EN;
MODIFY_REG(SPI1->CR1, SPI_CR1_BR, (SPI_CR1_BR_2 | SPI_CR1_BR_1 | SPI_CR1_BR_0));
    set_halfduplexTX_lsm303ah();
MODIFY_REG(SPI1->CR1, SPI_CR1_CPHA, SPI_CR1_CPHA);
MODIFY_REG(SPI1->CR1, SPI_CR1_CPOL, SPI_CR1_CPOL);
MODIFY_REG(SPI1->CR1, SPI_CR1_DFF, 0x00000000U);
MODIFY_REG(SPI1->CR1, SPI_CR1_SSM,  SPI_CR1_SSM);
MODIFY_REG(SPI1->CR2, SPI_CR2_SSOE, ((uint32_t)(SPI_CR1_SSM >> 16U)));
MODIFY_REG(SPI1->CR1, SPI_CR1_MSTR | SPI_CR1_SSI, (SPI_CR1_MSTR | SPI_CR1_SSI));
 
Later, we need to activate spi
Later, we need switch direction of data transfer on spi data line
 
 
-- 
With best regards, Kuznetcov Artem

**Comment by acassis** [comment]
Hi @artemopolus, NuttX already have SPI driver implemented and supply some macros to let you to communicate with your sensor. So, you just need to create a driver to communicate with your sensor and export it as a special device file inside /dev, similar to what Linux does. Please take a look at nuttx/drivers/sensors/ there are many examples there.

These drivers need to be initialized in the board code to be associated to an specific SPIn and its CS pin needs to be configured to be asserted correctly. There are some examples at boards/arm/stm32/stm32f103-minimum/src/ and many other boards.

This is very easy to do, but could be a little bit confusing initially for people coming from baremetal or from RTOS that are very baremetal-like. For people with experience developing Linux kernel driver it is very straightforward.

BTW, I think you don't need to open an issue here, it is better to ask these question at NuttX mailing list, you can subscribed to it from here: http://nuttx.incubator.apache.org/community/
