### ISSUE TITLE
EXTRAFLAGS appears in AFLAGS three times

### ISSUE THREAD

**Issue by yamt** [apache/incubator-nuttx#1688]
I only checked sim. but others might have similar issues.

when you do "make EXTRAFLAGS=foobar",
foobar appears in eg. AFLAGS three times.

it's a problem because some options are not idempotent.
eg. the following example was with EXTRAFLAGS="-fsanitize=address -mllvm -asan-stack=0 "

AS:  sim/up_setjmp64.S
/usr/local/Cellar/llvm/10.0.1/bin/clang -c -Wall -Wstrict-prototypes -Wshadow -Wundef -g -fstack-protector-all -fno-builtin -fno-common -isystem "/Users/yamamoto/git/nuttx/nuttx/include"  -D__KERNEL__ -fsanitize=address -mllvm -asan-stack=0  -pipe -I "/Users/yamamoto/git/nuttx/nuttx/arch/sim/src" -I "/Users/yamamoto/git/nuttx/nuttx/arch/sim/src/chip" -I "/Users/yamamoto/git/nuttx/nuttx/sched" -D__KERNEL__ -fsanitize=address -mllvm -asan-stack=0  -D__ASSEMBLY__ -I "/Users/yamamoto/git/nuttx/nuttx/arch/sim/src" -I "/Users/yamamoto/git/nuttx/nuttx/arch/sim/src/chip" -I "/Users/yamamoto/git/nuttx/nuttx/sched" -D__KERNEL__ -fsanitize=address -mllvm -asan-stack=0   sim/up_setjmp64.S  -o  up_setjmp64.o
clang (LLVM option parsing): for the --asan-stack option: may only occur zero or one times!
clang (LLVM option parsing): for the --asan-stack option: may only occur zero or one times!

**Comment by v01d** [comment]
@yamt I think I solved this in https://github.com/apache/incubator-nuttx/pull/1776
can you verify this removes your case of repeated flags in AFLAGS? The fix should apply to all *FLAGS.
