### ISSUE TITLE
Misc documentation issues

### ISSUE THREAD

**Issue by btashton** [apache/incubator-nuttx#1720]
Here are some minor documentation issues

- [ ] Bad references in the Root Directory and Environment Variables sections here https://nuttx.apache.org/docs/latest/quickstart/build_and_make.html
![image](https://user-images.githubusercontent.com/173245/92292407-f5584600-eed1-11ea-95e0-ee87ef463a69.png)

- [ ] Bad escape in "Install a Cross-Compiler Toolchain"  https://nuttx.apache.org/docs/latest/quickstart/quickstart.html
```
``/opt/gcc`
```

- [ ] Bad heading "#. Download Apache NuttX " https://nuttx.apache.org/docs/latest/quickstart/quickstart.html

- [ ] Number wrong (1) for all items https://nuttx.apache.org/docs/latest/quickstart/install.html#install-required-tools-all-platforms
- [ ] We list gperf as required for kconfig-frontends, but then install it afterwards.  Are we sure it is required? https://nuttx.apache.org/docs/latest/quickstart/install.html#install-required-tools-all-platforms

- [ ]  Gnu should be GNU
```
guides/drivers.rst:83:    * `GDB — the Gnu Debugger <https://www.gnu.org/software/gdb/>`_
quickstart/quickstart.rst:18:   `ARM Embedded Gnu Toolchain <https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm>`_
quickstart/debugging.rst:9:debugging using the Gnu Debugger (gdb).
quickstart/install.rst:171:`ARM Embedded Gnu Toolchain <https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm>`_
quickstart/running.rst:25:#. Launch the Gnu Debugger
quickstart/running.rst:28:   ARM Embedded Gnu Toolchain we downloaded in the Install step.
```

- [ ] Missing screenshot image https://nuttx.apache.org/docs/latest/quickstart/configuring.html#configuring
![image](https://user-images.githubusercontent.com/173245/92292847-40735880-eed4-11ea-95ca-d89015d8428c.png)

- [ ] We suggest editing `.config` which we never should do https://nuttx.apache.org/docs/latest/quickstart/debugging.html#debug-logging

**Comment by adamfeuer** [comment]
Thanks @btashton, I'm working on a PR to fix these issues.

**Comment by adamfeuer** [comment]
@btashton I don't really know much about whether gperf is really needed, we should investigate that; for now I moved the instruction before the kconfig-frontends install.

**Comment by adamfeuer** [comment]
@btashton https://github.com/apache/incubator-nuttx/pull/1722 should fix all these issues. I also fixed the section numbering in quickstart so all the instructions should be correct now.
