### ISSUE TITLE
sim:bthcisock build broken

### ISSUE THREAD

**Issue by btashton** [apache/incubator-nuttx#2085]
The `sim:bthcisock` build is broken failing to register the HCI interface

```
❯ sudo btmon
@ RAW Open: nuttx (privileged) version 2.22                  {0x0002} 22.803159
@ MGMT Event: Index Removed (0x0005) plen 0           {0x0001} [hci0] 22.803185
@ MGMT Event: Index Added (0x0004) plen 0             {0x0001} [hci0] 22.803198
@ RAW Close: nuttx        
```

```
❯ sudo setcap 'cap_net_raw,cap_net_admin=eip' ./nuttx
❯ ./nuttx 
ERROR: bthcisock_register() failed: -1

NuttShell (NSH) NuttX-9.1.0
nsh> 
```

**Comment by btashton** [comment]
@v01d would you mind taking a look at these two BLE issues on the 10.0 release.  I am working through functional test of the branch, so it will be a while before a circle back to debug.

**Comment by v01d** [comment]
I'll have a look. Last time it was working for me.

**Comment by v01d** [comment]
```
❯ sudo setcap 'cap_net_raw,cap_net_admin=eip' nuttx/nuttx
❯ nuttx/nuttx

NuttShell (NSH) NuttX-9.1.0
nsh> ifconfig
bnep0	Link encap:UNSPEC at DOWN

nsh> ifup bnep0
ifup bnep0...OK
nsh> ifconfig
bnep0	Link encap:UNSPEC at UP

nsh> 
```
Maybe you don't have your BT dongle up? Or you are already using it from some other app?

**Comment by btashton** [comment]
Nope, the code should be taking it down anyway and then opening it as a user socket. You tested the releases/10.0 branch right?  I can take a look later and see if I can figure out whats up.  Running into fair amount of partially broken configurations :/

**Comment by v01d** [comment]
Yes, this is for 10.0

**Comment by sebastianene07** [comment]
Can I help on this ? I have some experience with bluetooth devices.

**Comment by btashton** [comment]
@sebastianene07 I think it is something with my config since I wrote the code for it recently and @v01d has been using it a lot for his BLE work.  I'll be digging into it today.

**Comment by v01d** [comment]
Found the issue, see related PR. This is only on master though, so it does not need to block 10.0 release.

**Comment by btashton** [comment]
Hmm not this seems to be working fine on the 10.0 branch now.  I am not sure what was going on, maybe I accidentally ended up back on master.  I'll close this out.  Sorry for the extra noise @v01d
