### ISSUE TITLE
sim:duktape Broken Build

### ISSUE THREAD

**Issue by btashton** [apache/incubator-nuttx#2087]
The build is broken for `sim:duktape`

```
❯ ./nuttx
login: admin
password: 
User Logged-in!

NuttShell (NSH) NuttX-9.1.0
MOTD: username=admin password=Administrator
nsh> duk
Segmentation fault (core dumped)
```

**Comment by xiaoxiang781216** [comment]
@ no1wudi could you take a look the break?

**Comment by no1wudi** [comment]
> @no1wudi could you look at the break?

This program need 32K stack on sim, and about 8k on thumbv7m platform.

@btashton @xiaoxiang781216 Should we let a large enough stack (e.g. 64K) as default stack size for all platform ?

**Comment by xiaoxiang781216** [comment]
it's better to change duktape stack to 64KB in sim's defconfig.

**Comment by no1wudi** [comment]
it's ok, but may same broken also exist on other platform (like riscv)

**Comment by xiaoxiang781216** [comment]
But, no config in riscv enable duktape. if some one enable duktape in new config, he has to it set the stack size explicitly. Maybe, we should remove the default stack from duktape.

**Comment by btashton** [comment]
I'll close when I create the backport.
