### ISSUE TITLE
sim:rpserver segfault

### ISSUE THREAD

**Issue by btashton** [apache/incubator-nuttx#2094]
The `sim:rpserver` configuration segfaults
```
❯ sudo ./nuttx
Segmentation fault
```

This prevents also testing the `sim:rpproxy` configuration.

**Comment by xiaoxiang781216** [comment]
This is regressed by the change: https://github.com/apache/incubator-nuttx/pull/650. CONFIG_SIM_M32=y could fix this problem, but the change can't pass macOS build. We need enhance testbuild.sh and datlist to skip some special config on a particular host.

**Comment by btashton** [comment]
Is there a reason we know why it only works in 32bit mode?

**Comment by xiaoxiang781216** [comment]
This is the initial remoteproc design limitation:
https://lists.openampproject.org/pipermail/tsc/2019-October/000009.html
Since remoteproc/rpmsg is deployed on many OS(Linux, NuttX, Zephyr, FreeRTOS...), OpenAMP community need time to find a good mitigation path.

**Comment by btashton** [comment]
@xiaoxiang781216 If you can look at my PR over in the test repo, with that we can disable the rpserver/proxy targets as disabled for macOS and then change the config to M32=y which should resolve this issue.  The PR does not yet add these targets to the tweak list for macOS, so let me know if you want me to make that change.
