### ISSUE TITLE
nuttx-gdbinit uses symbol from unrelated application

### ISSUE THREAD

**Issue by v01d** [apache/incubator-nuttx#2388]
When trying to use nuttx-gdbinit, it complains that `g_statenames` is not defined. I found this symbol in `note_main.c` from note app. nuttx-gdbinit facility should not depend an a symbol from an unrelated app. The symbol should either by defined in nuttx itself or inside nuttx-gdbinit.

**Comment by v01d** [comment]
Actually, this array is static so I'm not even sure if this is the place where it is supposed to be defined. Also, this same information is defined in three places:

```
nuttx/fs/procfs/fs_procfsproc.c:static FAR const char *g_statenames[] =
apps/examples/thttpd/content/tasks/tasks.c:static const char *g_statenames[] =
apps/system/sched_note/note_main.c:static FAR const char *g_statenames[] =
```

I think the best is to define this information in one place, which will make it available to all required places, including openocd which can be made to retrieve it instead of define it itself.

**Comment by v01d** [comment]
@masayuki2009 it seems you authored this file. Where is this variable defined for you?

**Comment by btashton** [comment]
I think procfs is where is was supposed to be pulled from which is used by the `ps` command.

**Comment by v01d** [comment]
But it is static there as well

**Comment by v01d** [comment]
Ah, the symbol is still visible. I assumed it wouldn't. So maybe this place isn't such a bad place to have it defined I guess.
I will document that PROCFS needs to be enabled for this to work. Also, I would update openocd to use this then.
