### ISSUE TITLE
to introduce a new function timerfd_settime() and timerfd_gettime()

### ISSUE THREAD

**Issue by edbek** [apache/incubator-nuttx#268]
Is it possible to introduce a new function **timerfd_settime** () and **timerfd_gettime** ()?

**Comment by patacongo** [comment]
I would prefer not.  These are non-standard GLIBC functions.  NuttX follows the standards defined at OpenGroup.org which does not include these interfaces.

There are exceptions to this in the code base now, but I don't think we should proliferate non-standard interfaces.

**Comment by patacongo** [comment]
The solution would also required timerfd_create().  https://linux.die.net/man/2/timerfd_settime

While I don't advocate including non-standard interfaces in the OS, I would not oppose the inclusion of these GLIBC/Linux interfaces if they were properly implemented in the nuttx/fs directory (with new interfaces to sched/timer, were configurable, and had proper system calls implemented in syscall/.

**Comment by edbek** [comment]
yes, of course, the timerfd_create () function is also required. I think it would be very useful for this project to have such a set of functions:

timerfd_create ();
thimerfd_settime ();
thimerfd_gettime ();

Thank you in advance if they appear !

**Comment by xiaoxiang781216** [comment]
We can add eventfd and signalfd to the list too, these three API set is the good addition to POSIX since they strengthen the core UNIX design principle: Everything is a file.

**Comment by edbek** [comment]
I agree !

**Comment by patacongo** [comment]
eventfd APIs introduced with PR #1479.   PR #1479 does not address signalfd and timerfd interfaces, however.

**Comment by eerimoq** [comment]
Hello!

I'm interested in `timerfd_create()` as well. Does anyone have an implementation ready? If not, I might try to implement it myself.

**Comment by xiaoxiang781216** [comment]
@eerimoq as far as I know nobody start the work, it will be great to add timerfd support! Actually, you can reference the recent addition of eventfd PR #1479 and #1479.

**Comment by pkarashchenko** [comment]
Trying to address this issue in scope of https://github.com/apache/incubator-nuttx/pull/5014

**Comment by xiaoxiang781216** [comment]
Nice!

**Comment by xiaoxiang781216** [comment]
Ok, we support the final one(signalfd), great!
