### ISSUE TITLE
NUMBER:JACK - Improper generation of Initial Sequence Number in TCP stack

### ISSUE THREAD

**Issue by gustavonihei** [apache/incubator-nuttx#2839]
On February 10, 2021 Forescout Research Labs published another vulnerability report that affects multiple TCP/IP stacks.
**uIP** TCP/IP stack is among them, with the following description:
```
ISN generator is initialized with a constant value and has constant increments.
```
In fact, the description seems fit to NuttX TCP/IP stack. In https://github.com/apache/incubator-nuttx/blob/master/net/tcp/tcp_seqno.c, `g_tcpsequence` is initialized with 0, and each call to `tcp_nextsequence()` just increments the variable.

Link to the report:
https://www.forescout.com/company/blog/numberjack-forescout-research-labs-finds-nine-isn-generation-vulnerabilities-affecting-tcpip-stacks

**Comment by btashton** [comment]
Please in the future report security issues inline with our reporting policy so we can evaluate it responsibility.

https://www.github.com/apache/incubator-nuttx/tree/master/.github%2FSECURITY.md
