### ISSUE TITLE
Move C11 Atomic function definitions from ESP32-C3 to common code

### ISSUE THREAD

**Issue by gustavonihei** [apache/incubator-nuttx#3483]
GCC does not provide the low-level implementation of the C11 Atomic operations for CPUs that don't provide the appropriate ISA support **[1][2]**.
So the C11 atomic operations have been implemented **[3]** for ESP32-C3 with support from NuttX, since the ESP32-C3 RISC-V ISA does not implement the atomics (A) extension.
The same implementation could be reused by other CPUs that don't provide atomic load/store instructions, e.g. Cortex-M0+, which being based on the armv6-m does not provide the Load-Exclusive and Store-Exclusive instructions from armv7-m.

This is also required for using some C++ standard library functions, e.g. `std::mutex`.

**[1]** https://gcc.gnu.org/wiki/Atomic/GCCMM/LIbrary
**[2]** https://gcc.gnu.org/onlinedocs/gcc/_005f_005fatomic-Builtins.html
**[3]** https://github.com/apache/incubator-nuttx/blob/master/arch/risc-v/src/esp32c3/esp32c3_std_atomic.c

**Comment by xiaoxiang781216** [comment]
How about we these:

1. Move https://github.com/apache/incubator-nuttx/blob/master/arch/risc-v/src/esp32c3/esp32c3_std_atomic.c to libc as a general implementation
2. Move https://github.com/apache/incubator-nuttx/blob/master/arch/arm/src/armv7-m/gnu/arm_fetchadd.S, https://github.com/apache/incubator-nuttx/blob/master/arch/arm/src/armv7-a/arm_fetchadd.S, https://github.com/apache/incubator-nuttx/blob/master/arch/arm/src/armv8-m/arm_fetchadd.S and https://github.com/apache/incubator-nuttx/blob/master/arch/arm/src/armv7-r/arm_fetchadd.S to libc/machine as the arch specific implementation
3. Migrate up_testset to the new atomic api
