### ISSUE TITLE
make V=1 failed to run!

### ISSUE THREAD

**Issue by bhatmahadev6** [apache/incubator-nuttx#3691]
I am trying to run the nsh  build for arty_a7 and the build is failing at the make V=1
The Log is here:

riscv64-unknown-elf-ld: /home/iisclap/riscv64-unknown-elf-toolchain-10.2.0-2020.12.8-x86_64-linux-ubuntu14/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/libgcc.a(div.o): ABI is incompatible with that of the selected emulation:
  target emulation `elf64-littleriscv' does not match `elf32-littleriscv'
riscv64-unknown-elf-ld: failed to merge target specific data of file /home/iisclap/riscv64-unknown-elf-toolchain-10.2.0-2020.12.8-x86_64-linux-ubuntu14/bin/../lib/gcc/riscv64-unknown-elf/10.2.0/libgcc.a(div.o)
Makefile:158: recipe for target 'nuttx' failed
make[1]: *** [nuttx] Error 1
make[1]: Leaving directory '/home/iisclap/NUTTX/nuttx/arch/risc-v/src'
tools/Makefile.unix:396: recipe for target 'nuttx' failed
make: *** [nuttx] Error 2

I installed this toolchain : https://github.com/riscv/riscv-gnu-toolchain
also enabled multilib

**Comment by povauboin** [comment]
Hello,

I had a similar issue some time ago. It looks like you are linking with the wrong libgcc.a.

You might want to change:
https://github.com/apache/incubator-nuttx/blob/master/boards/risc-v/litex/arty_a7/scripts/Make.defs#L44
-ARCHCPUFLAGS = -march=rv32ima -mabi=ilp32
+ARCHCPUFLAGS = -march=rv32im -mabi=ilp32

make distclean 
./tools/configure.sh arty_a7:nsh
make -j V=1

**Comment by bhatmahadev6** [comment]
Hi changing 
+ARCHCPUFLAGS = -march=rv32imac -mabi=ilp32

solved the issue.!
