### ISSUE TITLE
using "simu" instead of "sim"

### ISSUE THREAD

**Issue by 0bijian0** [apache/incubator-nuttx#3695]
It's not a bug, it's an idea。I strongly recommend changing "sim" to "simu". The "sim" is easy to confuse, especially when using sim card.

**Comment by yamt** [comment]
sim is a well-established abbreviation for simulate.
simu is not.
i guess you can just use "nuttx simulator" and "sim card" when it's confusing.

**Comment by v01d** [comment]
This would be a breaking change in lots of places (including docs). I don't think the benefit of the rename are good enough to justify the work, IMHO.
