### ISSUE TITLE
Compile error with CONFIG_DEBUG_PWM_INFO

### ISSUE THREAD

**Issue by imchangchang** [apache/incubator-nuttx#4025]
In https://github.com/apache/incubator-nuttx/blob/master/arch/arm/src/stm32h7/stm32_pwm.c, the ```pwm_dumpregs``` function's [definition](https://github.com/apache/incubator-nuttx/blob/master/arch/arm/src/stm32h7/stm32_pwm.c#L1728) and [declaration](https://github.com/apache/incubator-nuttx/blob/master/arch/arm/src/stm32h7/stm32_pwm.c#L324) are not matched.

**Comment by xiaoxiang781216** [comment]
@imchangchang could you provide a patch?

**Comment by imchangchang** [comment]
> @imchangchang could you provide a patch?

Have created a PR for this. 
https://github.com/apache/incubator-nuttx/pull/4088.
