### ISSUE TITLE
Unnecessary download of ESP Wireless Drivers

### ISSUE THREAD

**Issue by TA1DB** [apache/incubator-nuttx#4194]
I am working with esp32-wrover-kit:wapi configuration. Whenever I do "make menuconfig" and "make", the build system loads the ESP Wireless Drivers again and again irrelevant of their being already downloaded. This is time consuming and loads the network for no reason. I think it will be beneficial if a solution can be found for this issue.

**Comment by Ouss4** [comment]
Thanks for reporting this.  I'll be taking a look.

**Comment by Ouss4** [comment]
> Whenever I do "make menuconfig" and "make"

Well, there is a `clean_context` in the way, that will delete what was downloaded.  I can fix this but it will break the `context`/`clean_context` symmetry. This is how I had it the very first time, download on `context` and delete on `distclean`, but put some extra effort to not break the symmetry (BTW, apps download packages are also only cleaned on `distclean`).

@xiaoxiang781216 do you have any inputs before I go ahead and do that?

**Comment by TA1DB** [comment]
@Ouss4 Thanks for your response. Please note; I use lvgl library as well (for example) , it is downloaded one time only after "make distclean" or in first configuration.

**Comment by Ouss4** [comment]
> @Ouss4 Thanks for your response. Please note; I use lvgl library as well (for example) , it is downloaded one time only after "make distclean" or in first configuration.

Yes, this is what I said about "apps packages cleaned on `distclean`", it means they won't be deleted during a `clean_context` which `menuconfig` is doing.
