### ISSUE TITLE
Missing semicolon in threads.h

### ISSUE THREAD

**Issue by fxschauber** [apache/incubator-nuttx#4393]
https://github.com/apache/incubator-nuttx/blob/07d528fd8dcbc7b028c636441a9b6f25c23c822c/include/threads.h#L79

**Comment by xiaoxiang781216** [comment]
@fxschauber could you provide a patch? Thanks.

**Comment by acassis** [comment]
@fxschauber @xiaoxiang781216 I think adding ";" will add two ";" in the code with this CODE, see:
```
CODE int (*au_reset)(FAR struct adc_dev_s *dev);
```

**Comment by acassis** [comment]
@fxschauber you are right, looking other examples I can see it is missing the ";"

**Comment by fxschauber** [comment]
> @fxschauber could you provide a patch? Thanks.

Sorry for the dumb question but I've never contributed, do I need to fork then do a pull-request? Is there a README of the procedure somewhere?

**Comment by acassis** [comment]
@fxschauber it is not a dumb question, in fact it is our fault and we will fix it.

Yes, please create a fork, add your commit to your branch and create a pull request.

**Comment by Ouss4** [comment]
> Is there a README of the procedure somewhere?

https://nuttx.apache.org/docs/latest/contributing/making-changes.html

**Comment by acassis** [comment]
Thank you @Ouss4 in fact I look there and missed the contribute session, it was at the end... my fault
