### ISSUE TITLE
Incorrect type in thrd_join (threads.h)

### ISSUE THREAD

**Issue by fxschauber** [apache/incubator-nuttx#4396]
https://github.com/apache/incubator-nuttx/blob/07d528fd8dcbc7b028c636441a9b6f25c23c822c/include/threads.h#L162-L163

As pthread_addr_t is a void* type, `value` shouldn't be declared as a pointer to pthread_addr_t on line 162.

pthread_join  prototype is  `int pthread_join(pthread_t thread, void **value_ptr);`

**Comment by gustavonihei** [comment]
Thanks @fxschauber for reporting the issue.
I've submitted #4445 for addressing this and some other issues that were present as well on the C11 Threads API implementation.
