### ISSUE TITLE
nucleo-g431kb build error

### ISSUE THREAD

**Issue by daniel-p-carvalho** [apache/incubator-nuttx#4510]
I am trying to build nucleo-g431kb:nsh configuration but I getting the following error
  $arm-none-eabi-ld: Error: unable to disambiguate: -nostartfiles (did you mean --nostartfiles ?)

Probably this is related with commits made on Sep 7 since I can build this configuration up to Sep 6.

**Comment by Ouss4** [comment]
This is related to the following:
- https://github.com/apache/incubator-nuttx/pull/3900
- https://github.com/apache/incubator-nuttx/pull/3836
- https://github.com/apache/incubator-nuttx/issues/3826

cc @xiaoxiang781216 @yamt

**Comment by pkarashchenko** [comment]
@daniel-p-carvalho please feedback if the issue is still relevant. I tried to rebuild nucleo-g431kb:nsh example and it succeeded.

**Comment by daniel-p-carvalho** [comment]
I am out of office... I will check this tomorrow.

Em seg., 10 de jan. de 2022 17:50, Petro Karashchenko <
***@***.***> escreveu:

**Comment by pkarashchenko** [comment]
Is the issue still relevant or it can be closed?

**Comment by pkarashchenko** [comment]
@daniel-p-carvalho Is the issue still relevant or it can be closed?

**Comment by daniel-p-carvalho** [comment]
Hello Petro,

I am able to build and run nucleo-g431kb:nsh configuration.

Daniel Pereira de Carvalho


Em seg., 4 de jul. de 2022 às 07:36, Petro Karashchenko <
***@***.***> escreveu:
