### ISSUE TITLE
quickstart install instructions don't quite work (tar ball top-level dir misnamed)

### ISSUE THREAD

**Issue by craigcomstock** [apache/incubator-nuttx#4562]
Following instructions here: http://nuttx.apache.org/docs/latest/quickstart/install.html
and then http://nuttx.apache.org/docs/latest/quickstart/compiling.html (on OSX, but I don't think that's the issue)

The tarballs have odd names which don't work with the compiling instructions: `apache-incubator-nuttx-apps-d8757a6` and `apache-incubator-nuttx-a5406c6`. If I rename things work fine.

So maybe a change in docs or in tarball generation? Not sure which.

**Comment by Ouss4** [comment]
Github is appending the commit SHA to the directories names.  I guess they can just be renamed when extracted.

**Comment by acassis** [comment]
@craigcomstock at least on Linux you can use this command:
$ tar zxf apps.tar.gz --one-top-level=apps --strip-components 1

**Comment by craigcomstock** [comment]
@acassis yes, I did do that, just wasn't sure which way to go in terms of fixing the docs or tarballs. :+1: I am building happily on osx. Looks like the doc fix is the choice. Thanks!
