### ISSUE TITLE
ramdisk can be created,but mkfatfs /dev/ram0 falied with errno = 6

### ISSUE THREAD

**Issue by yanyunyouyou** [apache/incubator-nuttx#5020]
I used stm32f429i-disco:nsh configuration example ,and just enable the fat filesystem . The ramdisk can be created ,but mkfatfs can not work.  
![图片](https://user-images.githubusercontent.com/38059431/146554391-c5313629-081f-4c60-8b11-1cf2c120eaa3.png)

**Comment by anjiahao1** [comment]
try it:
```
mkrd -m 10 -s 512 1024
mount -t fatfs -o forceformat /dev/ram10 /data
```

**Comment by pkarashchenko** [comment]
@yanyunyouyou is the issue still relevant or you are satisfied with the answer?

**Comment by yanyunyouyou** [comment]
![无标题](https://user-images.githubusercontent.com/38059431/148948847-ab3f60f9-cd8b-4fbb-a63a-ce4cc6df2e55.png)
It took me a long time to solve this problem. The main reason is that I use WSL and vscode. Some incorrect configurations lead to incorrect header files. I changed to Ubuntu 18.04, recompiled, and the command can be executed. Thank anjiahao1 for the advice, but the answer is wrong. Please see my screenshot.

**Comment by yanyunyouyou** [comment]
> @yanyunyouyou is the issue still relevant or you are satisfied with the answer?
     
![Uploading 无标题.png…]()
It took me a long time to solve this problem. The main reason is that I use WSL and vscode. Some incorrect configurations lead to incorrect header files. I changed to Ubuntu 18.04, recompiled, and the command can be executed. Thank anjiahao1 for the advice, but the answer is wrong. Please see my screenshot.

**Comment by pkarashchenko** [comment]
Yes. `mount` does not know what is `-t fatfs` and `vfat` does not have `-o forceformat` option (it is from `littlefs`).
So if I understand correctly the issue is resolved and can be closed?

**Comment by yanyunyouyou** [comment]
Yes，it can be closed now。Thank you。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Petro ***@***.***&gt;; 
发送时间: 2022年1月12日(星期三) 上午7:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/incubator-nuttx] ramdisk can be created,but mkfatfs /dev/ram0 falied with errno = 6 (Issue #5020)





 
Yes. mount does not know what is -t fatfs and vfat does not have -o forceformat option (it is from littlefs).
 So if I understand correctly the issue is resolved and can be closed?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chenzhihong007** [comment]
In my case, nsh can't found mkfatfs command. How can I configuration to enable mkfatfs? Thank you!
![image](https://user-images.githubusercontent.com/109498998/236416066-e17894a3-7346-4191-b94a-134514378e1a.png)

**Comment by TimJTi** [comment]
From menuconfig, type a forward slash and it will open a search function. Type MKFATFS and it will show you that FSUTILS_MKFATFS is what you need, and it is dependent on FS_FAT etc. It even tells you if those dependencies are enabled.

 

You can type the number of the relevant search result (1, in this case) and it will take you directly to the menuconfig entry, assuming the dependencies allow it to be visible.

 

HTH!

**Comment by yanyunyouyou** [comment]
nuttx玩起了太累了，加油吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月5日(星期五) 晚上6:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/nuttx] ramdisk can be created,but mkfatfs /dev/ram0 falied with errno = 6 (Issue #5020)





 
I got it, thank you very much!
