### ISSUE TITLE
TCP/UDP source port selection should be random

### ISSUE THREAD

**Issue by normanr** [apache/incubator-nuttx#5068]
Currently the TCP/UDP port base is selected with:
```
g_last_tcp_port = clock_systime_ticks() % 32000;
if (g_last_tcp_port < 4096)
  {
    g_last_tcp_port += 4096;
  }
```
and "the next available port" is just incremented from there (with wrap around). This results in devices using the same ports when they're started up (which causes weird results because servers think connections are already open when they're not).

It would be better to use a random number on every selection (instead of plain increment starting from a time based number) as many platforms (even tiny embedded ones) have true random number generators these days and can seed the random pool in `board_init_rngseed()`

**Comment by adiroy05** [comment]
I will fix it assigne to me

**Comment by xiaoxiang781216** [comment]
Fixed by https://github.com/apache/incubator-nuttx/pull/6154
