### ISSUE TITLE
Replace all place which use semaphore as lock with mutex wrapper

### ISSUE THREAD

**Issue by xiaoxiang781216** [apache/incubator-nuttx#5184]
See the discussion: https://github.com/apache/incubator-nuttx/pull/5070 and https://www.mail-archive.com/dev@nuttx.apache.org/msg07312.html

**Comment by pkarashchenko** [comment]
@xiaoxiang781216 will we improve mutex wrapper to check for holder before releasing a mutex or a separate ticket should be created for that? Currently mutex can be released from a task that is not holding it.

**Comment by xiaoxiang781216** [comment]
it can be added in the separate PR. Maybe need to enabled in the debug mode to save the space.

**Comment by pkarashchenko** [comment]
I think that probably a good way will be to move priority inheritance from sem to mutex and clean-up priority inheritance APIs for semaphores after we switch to mutexes in code

**Comment by xiaoxiang781216** [comment]
Yes, this is the safe path to fix the priority inheritance issue.
