### ISSUE TITLE
make: *** No rule to make target 'byte', needed by 'differ'.  Stop.

### ISSUE THREAD

**Issue by pkarashchenko** [apache/incubator-nuttx#5255]
Sometimes when running `make` few times in a row compilation fails with `make: *** No rule to make target 'byte', needed by 'differ'.  Stop.`

**Comment by Ouss4** [comment]
Can you grab the output of `make V=1` when that happens?

**Comment by xiaoxiang781216** [comment]
I hit too, but pass in the next invocation.

**Comment by raiden00pl** [comment]
Just had a luck to capture this error with `make V=1`. Unfortunately, there is nothing useful to see. Absolutely nothing :)

```
[raiden00:~/git/RTOS/nuttx/nuttx]$ make V=1                                                                                                                                                                                                                                         
make: *** No rule to make target 'byte', needed by 'differ'.  Stop.
```

**Comment by fjpanag** [comment]
I am getting the same error, but only on my Fedora **35** machine.  
On Fedora **34** this issue does not appear.  
(Both systems are fully updated.)

I don't know if this is of any help.

**Comment by AlanRosenthal** [comment]
Please run `V=1 make --context`. it might be a lot of output
