### ISSUE TITLE
Error: unaligned opcodes detected in executable segment

### ISSUE THREAD

**Issue by acassis** [apache/incubator-nuttx#5449]
There is some aligment error in nx_eventhandler.c:
```
CC:  nxmu/nx_eventhandler.c
{standard input}: Assembler messages:
{standard input}: Error: unaligned opcodes detected in executable segment
make[1]: *** [Makefile:206: bin/nx_eventhandler.o] Error 1
make[1]: Leaving directory '/home/alan/nuttxspace/nuttx/libs/libnx'
make: *** [tools/LibTargets.mk:178: libs/libnx/libnx.a] Error 2
```

I didn't look the root causes yet, but this post has more info about this kind of reported error: https://stackoverflow.com/questions/32687459/error-unaligned-opcodes-detected-in-executable-segment

**Comment by pkarashchenko** [comment]
Could you please add steps to reproduce this issue?

**Comment by acassis** [comment]
@pkarashchenko the issue can be easily reproduced using this .config : https://pastebin.com/raw/hc5MZfJH

**Comment by xiaoxiang781216** [comment]
Can we close this issue now?

**Comment by pkarashchenko** [comment]
@xiaoxiang781216 yes. I was expecting that it will be closed automatically
