### ISSUE TITLE
nxstyle: "Multiple data definitions" false alarm

### ISSUE THREAD

**Issue by yamt** [apache/incubator-nuttx#627]
nxstyle complains "Multiple data definitions" on the following line in apps/examples/module/module_main.c

    static const char g_write_string[] = "Hi there, installed driver\n";

it seems it is confused with "," in the string.

**Comment by patacongo** [comment]
Isn't this the same as issue #387

**Comment by patacongo** [comment]
Isn't this the same as #387

**Comment by yamt** [comment]
it seems same. thank you.
