### ISSUE TITLE
nxstyle: "Operator/assignment must be preceded with whitespace"

### ISSUE THREAD

**Issue by yamt** [apache/incubator-nuttx#628]
nxstyle doesn't like the following line in apps/examples/sotest/sotest_main.c

      testfunc = (CODE void (*)(FAR const char *))dlsym(handle2, "testfunc1");

to me, the style seems perfectly fine.

**Comment by xiaoxiang781216** [comment]
> nxstyle doesn't like the following line in apps/examples/sotest/sotest_main.c
> 
> ```
>   testfunc = (CODE void (*)(FAR const char *))dlsym(handle2, "testfunc1");
> ```
> 
> to me, the style seems perfectly fine.

I guess nxstyle like this:
```
 testfunc = (CODE void ( * )(FAR const char *))dlsym(handle2, "testfunc1");
```

**Comment by yamt** [comment]
@xiaoxiang781216 
actually it doesn't.

    error: Space follows left parenthesis
    error: Space precedes right parenthesis

**Comment by pkarashchenko** [comment]
Seems to be fixed by https://github.com/apache/incubator-nuttx/pull/4880

**Comment by xiaoxiang781216** [comment]
So, let's close this issue.
