### ISSUE TITLE
NUCLEO-L496ZG-P:   no nsh access

### ISSUE THREAD

**Issue by TregliaRaphael** [apache/incubator-nuttx#6566]
Hi,
i'm trying to flash default configuration for the NUCLEO-L496ZG-p board but the nsh console is stuck in readline (as if i wasn't able to send any data to feed the readline throught UART). Let me go in deeper.
i'm cloning current master nuttx and apps 
nuttx commit: 881902d2cdf84902863cf848fb506be1613c8ac1
apps commit: 943df4cb6039072cbc2eb66c02311b6244bd1e95

**Steps:**
```
mkdir folder_test
cd folder_test
Cloning apps & nuttx repo
cd nuttx
./tools/configure.sh -l nucleo-l496zg:nsh
make oldconfig
make

st-flash write nuttx.bin 0x8000000
sudo screen /dev/ttyACM0 115200
```
**Results**:

The board blink correctly and is booting. I'm able to GDB in but i'm stuck in nsh_main readline().
It doesn't do temporary blue blinks like the last example i'hv done on the nucleo-144:f767-nsh (this one was working ez)
i tried screen command on the STLINKv2-1 USB directly and on the UART3 as mentionned in the README. But i'm unable to access the nsh

I don't have anymore to give except that the Nucleo board i'm using is totally brand new (just few plugs / no burn i promess)

Hope anyone can help me or give me advices. I'm know very well nuttx as PX4 user but not as new app creator. It seems that i'm not able to talk to the nsh process

Thanks you !

**Comment by ALTracer** [comment]
@TregliaRaphael Why are you using commit from master? Have you tried checking out releases/10.3 branch for both nuttx.git and apps.git?

Other than that I can only recommend checking GPIO pin mappings in your board.h and Kconfig options regarding USART and console selection. I don't have any relatives of STM32L4.
