### ISSUE TITLE
bch_read/bch_write function: the new position of the filep was set to be bad value while read/write actual length is less than the expexted length.

### ISSUE THREAD

**Issue by zdd2016** [apache/incubator-nuttx#6619]
bch_read/bch_write function: the new position of the filep was set to be bad value while read/write actual length is less than the expexted length.

1.  bch_read:
     ret = bchlib_write(bch, buffer, filep->f_pos, len);
      if (ret > 0)
        {
          filep->f_pos += len; 
        }

2.  bch_write:
     ret = bchlib_write(bch, buffer, filep->f_pos, len);
      if (ret > 0)
        {
          filep->f_pos += len;
        }

**Comment by xiaoxiang781216** [comment]
@zdd2016 Could you send a PR fix this issue? Thanks.

**Comment by xiaoxiang781216** [comment]
@zdd2016 fixed here: #6633

**Comment by zdd2016** [comment]
> @zdd2016 fixed here: #6633

OK
