### ISSUE TITLE
round() problems with NaN

### ISSUE THREAD

**Issue by nealef** [apache/incubator-nuttx#6767]
`round()` and `roundf()` (and presumably `roundl()`) don't return the correct value for NaN. Instead it is returning 0. Do these functions require a check such as:
```
  if (isinf(x) || isnan(x))
    return (x);
 ```
Prior to performing the rounding operation? (The check for infinity just saves having to go through the rest of the process.)

**Comment by fjpanag** [comment]
@nealef Thank you for pointing this out.

This is a fairly trivial fix. Would you like to contribute to NuttX by submitting a PR?
