### ISSUE TITLE
Missing extern C {} linkage wrapper for uname() in utsname.h

### ISSUE THREAD

**Issue by DuaneSkelton** [apache/incubator-nuttx#6859]
This is the only header in sys/include that does not have function prototypes wrapped in extern C {} guards. Was unable to link to the libc.a from a Nuttx application.

**Comment by xiaoxiang781216** [comment]
Could you create a patch to fix it? Thanks.

**Comment by DuaneSkelton** [comment]
https://github.com/apache/incubator-nuttx/pull/6860
