### ISSUE TITLE
Build / Linux (arm-05)  uses old pico-sdk.

### ISSUE THREAD

**Issue by curuvar** [apache/incubator-nuttx#7022]
There is a new version of pico-sdk that contains firmware needed to use the WiFi chip on the RaspberryPi Pico W.   

No test build that uses the Pico W's WiFi can succeed until this library is updated.

**Comment by xiaoxiang781216** [comment]
can you update the download script to point the lasts release?

**Comment by curuvar** [comment]
I don't know how to update the download script.  If I knew where it was I could probably figure that out, but I don't even know that.  

For my build here I just grabbed the latest pico-sdk from https://github.com/raspberrypi/pico-sdk and set the PICO_SDK_PATH environment variable to point to it.
