### ISSUE TITLE
Do we have a plan to support ARTERY(雅特力) MCU?

### ISSUE THREAD

**Issue by TompsonTan** [apache/incubator-nuttx#7049]
Do we have a plan to support artery mcu， especially AT32F435/437 ？
想问下，接下来NUTTX有计划支持雅特力的MCU吗？特别是新出的 AT32F435/437

**Comment by xiaoxiang781216** [comment]
It depends on manufacture.

**Comment by acassis** [comment]
@TompsonTan you can ask the manufacturer to add support, this is the only way they know that there are users for it! If you have a company and want to create some product with it your chance to get attention will increase!

**Comment by TompsonTan** [comment]
OK, thank you.
