### ISSUE TITLE
Netinit bringup for multiple types of network device interfaces

### ISSUE THREAD

**Issue by haitomatic** [apache/incubator-nuttx#7163]
https://github.com/apache/incubator-nuttx-apps/blob/master/netutils/netinit/netinit.c 
According to this, I am wondering how can we bring up all interfaces if we have multiple of them. In my application, I need to enable both ETHERNET and socketCAN at the same time. However, the CONFIG_NET_ETHERNET shadows over CONFIG_NET_CAN and therefore, though registered as a network device, the can0 iface is never brought up. This apparently is not only between socketCAN and Ethernet but also between all other interfaces like wlan, bluetooth,etc.

**Comment by pkarashchenko** [comment]
Or you may not boot into NSH, but to custom entry point and use `netlib_ifup()`.

**Comment by haitomatic** [comment]
thanks for the comments. Now I see it clear. `rcS` is a good place to bring up all other non-ethernet interfaces :+1:
