### ISSUE TITLE
arch: cxd56xx: Compile error in cxd56_gnss.c

### ISSUE THREAD

**Issue by SPRESENSE** [apache/incubator-nuttx#7234]
Improper code refactoring by https://github.com/apache/incubator-nuttx/pull/7191 causes a compile error.

bdeaea3742 Remove the unnessary empty line after label

```
chip/cxd56_gnss.c:2858:7: error: label 'err' used but not defined
 2858 |       goto err;
      |       ^~~~
```

**Comment by jerpelea** [comment]
@SPRESENSE  please open a PR with the fix
