### ISSUE TITLE
nxstyle reporting error: Space precedes right parenthesis

### ISSUE THREAD

**Issue by acassis** [apache/incubator-nuttx#725]
There are case where we need to align the right parenthesis.

(it appears dealigned here, but if you copy to text editor you will see it is aligned)

const struct trace_msg_t g_usb_trace_strings_deverror[] =
{
  TRACE_STR(STM32L4_TRACEERR_ALLOCFAIL            ),
  TRACE_STR(STM32L4_TRACEERR_BADCLEARFEATURE      ),
  TRACE_STR(STM32L4_TRACEERR_BADDEVGETSTATUS      ),
  TRACE_STR(STM32L4_TRACEERR_BADEPGETSTATUS       ),
  TRACE_STR(STM32L4_TRACEERR_BADEPNO              ),
  TRACE_STR(STM32L4_TRACEERR_BADEPTYPE            ),
  TRACE_STR(STM32L4_TRACEERR_BADGETCONFIG         ),
  TRACE_STR(STM32L4_TRACEERR_BADGETSETDESC        ),
  TRACE_STR(STM32L4_TRACEERR_BADGETSTATUS         ),
  TRACE_STR(STM32L4_TRACEERR_BADSETADDRESS        ),

Please fix nxstyle to access this code beautification

**Comment by patacongo** [comment]
> There are case where we need to align the right parenthesis.

Why.  It is unnecessary to align right parentheses and difficult to maintain.  It is also contrary to the coding standard which states explicitly in paragraph 1.6 Parentheses:  "Never space before the right parentheses. There should never be space before a right parenthesis ()). "

This is not an issue.  It is a proposed violation of the coding standard.  I will close the issue.
